global:
  scrape_interval:     1s
  evaluation_interval: 15s
  external_labels:
      monitor: 'docker-host-alpha'

rule_files:
  - "alert.rules.yml"
  
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']