{
 "title": "Docker Host & Container Overview",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": "label_values(container_group)" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic on Node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage on Node",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Running Containers (by Container Group)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",container_group=\"\"}[$interval]))",
     "legendFormat": "Monitoring"
    }
   ]
  },
  {
   "title": "Free and Used Disk Space on Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(node_filesystem_free_bytes{fstype=\"ext4\"})",
     "legendFormat": "Free Disk Space"
    },
    {
     "expr": "max(node_filesystem_size_bytes{fstype=\"ext4\"} - node_filesystem_free_bytes{fstype=\"ext4\"})",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "CPU Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Available Memory on Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"})",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_memory_rss{id=\"/\"}",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "sum(container_memory_rss)", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "System Load on Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"^node_load.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "cAdvisor Version: {{cadvisorVersion}}"
    },
    {
     "expr": "prometheus_build_info",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "node_exporter_build_info",
     "legendFormat": "Node-Exporter Version: {{version}}"
    },
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "Docker Version: {{dockerVersion}}"
    },
    { "expr": "cadvisor_version_info", "legendFormat": "Host OS Version: {{osVersion}}" },
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "Host Kernel Version: {{kernelVersion}}"
    }
   ]
  },
  {
   "title": "Cached Memory per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_cache{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}