{
 "title": "elasticsearch-ds",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Nodes - CPU USAGE",
   "type": "graph",
   "description": "CPU usage of all the nodes of the system",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{name=~\".*_es0.*\"}[1m])) BY (instance, name))/4"
    }
   ]
  },
  {
   "title": "All Nodes - NETWORK BYTES",
   "type": "graph",
   "description": "Traffic in bytes for every Nodes in the Elasticsearch cluster",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_network_receive_bytes_total{name=~\".*_es0.*\"}[1m])) BY (instance, name))"
    },
    {
     "expr": "(sum(rate(container_network_transmit_bytes_total{name=~\".*_es0.*\"}[1m])) BY (instance, name))"
    }
   ]
  },
  {
   "title": "es01 - MEMORY USAGE",
   "type": "graph",
   "description": "The amount of memory used by the es01 container in bytes",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"tp2_es01_1\"}",
     "legendFormat": "es01_1"
    }
   ]
  },
  {
   "title": "es01_1 - CPU USAGE",
   "type": "graph",
   "description": "The average amount of CPU usage by the container es01",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"tp2_es01_1.*\"}[1m]))/4",
     "legendFormat": "es01_1"
    }
   ]
  },
  {
   "title": "es01_1 - NETWORK BYTES",
   "type": "graph",
   "description": "Network bytes per seconds for  the container es01_1",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total{name=~\".*_es01_1\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum(container_network_transmit_bytes_total{name=~\".*_es01_1\"})",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "es02_1 - MEMORY USAGE",
   "type": "graph",
   "description": "Memory used by  the container es02_1",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".*_es02_1\"}",
     "legendFormat": "es02_1"
    }
   ]
  },
  {
   "title": "es02_1- CPU USAGE",
   "type": "graph",
   "description": "The average amount of CPU usage by 1 minute for the es02_1 container",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".*_es02_1\"}[1m]))/4\n",
     "legendFormat": "es02_1"
    }
   ]
  },
  {
   "title": "es02_1 - NETWORK BYTES",
   "type": "graph",
   "description": "Network bytes per seconds for  the container es02_1",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total{name=~\".*_es02_1\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum(container_network_transmit_bytes_total{name=~\".*_es02_1\"})",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "es02_2 - MEMORY USAGE",
   "type": "graph",
   "description": "Memory used by the container es02_2",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".*_es02_2\"}",
     "legendFormat": "es02_2"
    }
   ]
  },
  {
   "title": "es02_2 - CPU USAGE",
   "type": "graph",
   "description": "The average amount of CPU usage by 1 minute for the es02_2 container",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".*_es02_2\"}[1m]))/4",
     "legendFormat": "es02_2"
    }
   ]
  },
  {
   "title": "es02_2 - NETWORK BYTES",
   "type": "graph",
   "description": "Network bytes per seconds for  the container es02_2",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total{name=~\".*_es02_2\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum(container_network_transmit_bytes_total{name=~\".*_es02_2\"})",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Host - CPU USAGE",
   "type": "graph",
   "description": "The average amount of CPU time spent in system mode, per second, over the last minute (in seconds)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"system\"}[1m]))",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Host - MEMORY USAGE",
   "type": "graph",
   "description": "The used memory by the host system",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemAvailable_bytes)",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Host - NETWORK BYTES",
   "type": "graph",
   "description": "The average network traffic received, per second, over the last minute (in bytes)",
   "gridPos": { "h": 9, "w": 13, "x": 5, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[1m])"
    }
   ]
  }
 ]
}